# Generated by Django 3.2.6 on 2022-01-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(blank=True, help_text='author id Value', null=True, verbose_name='author id Value')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=500, verbose_name='summary')),
                ('content', models.CharField(max_length=500, verbose_name='content')),
            ],
        ),
    ]
